### ISSUE TITLE
[BUG] Pipe bomb sound doesn't play on sent messages

### ISSUE THREAD

**Issue by Blexyel** [RoootTheFox/gd-pipebomb#1]
The explosion sound doesn't seem to play when going to your own sent messages, it only plays the flash.

This is all it shows in the logs
```
21:26:29 INFO  [Main] [Pipe bomb]: load - msg 81151701 last temp
21:26:29 INFO  [Main] [Pipe bomb]: pipe bomb :33
```

**Comment by RoootTheFox** [comment]
if it logs "pipe bomb :33" the detection logic ran successfully - you either have the SFX volume at 0 or didn't enable the pipe bomb sound effect in the mods settings (its disabled by default)

**Comment by Blexyel** [comment]
oh well, stoopid
